{
  "firstName": "John",
  "age": 30,
  "address": 
      { "streetAddress": "107 Linkside Ct",
        "city": "Woodstock",
        "state": "GA",
        "postalCode": "30189"
      },
  "lastName": "Neal",
  "phoneNumber":
  [
    {
      "type": "home",
      "number": "770-843-4926"
    },
    {
      "type": "work",
      "number": "770-494-0061"
    }
  ]
}