{
  "firstName": "",
  "age": ,
  "address": 
      { "streetAddress": "",
        "city": "",
        "state": "",
        "postalCode": ""
      },
  "lastName": "",
  "phoneNumber":
  [
    {
      "type": "",
      "number": ""
    },
    {
      "type": "work",
      "number": ""
    }
  ]
}
